### ISSUE TITLE
docker not working

### ISSUE THREAD

**Issue by jdtorrenegraneiu** [Erikvl87/docker-languagetool#12]
The following configuration is passed to LanguageTool:
+ java -Xms256m -Xmx512m -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8010 --public --allow-origin '*' --config config.properties
languageModel=/ngrams
2021-01-15 21:48:36 -0800 INFO org.languagetool.server.DatabaseAccess Not setting up database access, dbDriver is not configured
2021-01-16 05:48:36 +0000 WARNING: running in HTTP mode, consider running LanguageTool behind a reverse proxy that takes care of encryption (HTTPS)

2021-01-16 05:48:36 +0000 WARNING: running in public mode, LanguageTool API can be accessed without restrictions!

2021-01-16 05:48:37 +0000 Setting up thread pool with 10 threads
2021-01-16 05:48:37 +0000 Starting LanguageTool 5.2 (build date: 2020-12-30 14:55, eb572bf) server on http://localhost:8010...
2021-01-16 05:48:37 +0000 Server started
2021-01-15 21:48:44 -0800 ERROR org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default', sending HTTP code 400. Access from 192.168.1.10, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75, User agent param: null, Referrer: null, language: en-us, h: 1, r: 1, time: 2m: ALL, l: DEFAULT, Stacktrace follows:java.lang.IllegalArgumentException: This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default

at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:190)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by Erikvl87** [comment]
Could you include the details of your HTTP request in the ticket? The errors `You have not specified any parameters` and the `IllegalArgumentException` seem to indicate an issue related to your request.

Additionally, could you verify if a different (simple) request does work, e.g. `http://localhost:8010/v2/check?language=en-US&text=An exmpl txt to scan`

**Comment by Erikvl87** [comment]
I am closing this issue due to inactivity. Please reopen this ticket and include the details of your HTTP request if you are still experiencing issues.

**Comment by kphanipavan** [comment]
To anyone facing similar issue, make sure you include `v2` at the end of custom url. Sample: `http://10.9.8.1:8010/v2`.
