### ISSUE TITLE
libstdc++.so.6 missing

### ISSUE THREAD

**Issue by tja** [Erikvl87/docker-languagetool#16]
Trying to use a language other than `en-US` (such as `de-DE` with the word `autohaus`) will result in the following server error:

```
 # BridJ: dlopen error when loading /tmp/BridJExtractedLibraries277612737966416782/libhunspell.so : Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/BridJExtractedLibraries277612737966416782/libhunspell.so)
2021-03-05 12:31:00 +0000 ERROR org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: German (Germany)): <sent
     at org.languagetool.server.TextChecker.checkText(TextChecker.java:397)
     at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:148)
     at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:73)
     at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:180)
     at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
     at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
     at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
     at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
     at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
     at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     at java.base/java.lang.Thread.run(Thread.java:834)
 Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: German (Germany)): <sentcontent>autohaus</sentcontent>
     at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
     at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
     at org.languagetool.server.TextChecker.checkText(TextChecker.java:378)
     ... 12 more
 Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: German (Germany)): <sentcontent>autohaus</sentcontent>
     at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1186)
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:930)
     at org.languagetool.server.TextChecker.getPipelineResults(TextChecker.java:645)
     at org.languagetool.server.TextChecker.getRuleMatches(TextChecker.java:594)
     at org.languagetool.server.TextChecker.access$000(TextChecker.java:56)
     at org.languagetool.server.TextChecker$1.call(TextChecker.java:371)
     at org.languagetool.server.TextChecker$1.call(TextChecker.java:364)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     ... 3 more
 Caused by: java.lang.RuntimeException: Could not check sentence (language: German (Germany)): <sentcontent>autohaus</sentcontent>
     at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1830)
     at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1724)
     at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1696)
     at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1182)
     ... 10 more
 Caused by: java.lang.RuntimeException: Could not create hunspell instance. Please note that LanguageTool supports only 64-bit platforms (Linux, Windows, Mac) and that it requires a 64-bit JVM (Java).
     at org.languagetool.rules.spelling.hunspell.Hunspell.<init>(Hunspell.java:51)
     at org.languagetool.rules.spelling.hunspell.Hunspell.getInstance(Hunspell.java:62)
     at org.languagetool.rules.spelling.hunspell.HunspellRule.init(HunspellRule.java:368)
     at org.languagetool.rules.de.GermanSpellerRule.init(GermanSpellerRule.java:1065)
     at org.languagetool.rules.spelling.hunspell.HunspellRule.ensureInitialized(HunspellRule.java:342)
     at org.languagetool.rules.spelling.hunspell.HunspellRule.match(HunspellRule.java:122)
     at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:1255)
     at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1803)
     ... 13 more
 Caused by: java.lang.UnsatisfiedLinkError: 'long dumonts.hunspell.bindings.HunspellLibrary.Hunspell_create(long, long)'
     at dumonts.hunspell.bindings.HunspellLibrary.Hunspell_create(Native Method)
     at dumonts.hunspell.bindings.HunspellLibrary.Hunspell_create(HunspellLibrary.java:25)
     at org.languagetool.rules.spelling.hunspell.Hunspell.<init>(Hunspell.java:45)
     ... 20 more
```

It seems that the library `libstdc++.so.6` is missing from the distribution.

P.S.: Thanks for the project!

**Comment by Erikvl87** [comment]
Thanks for pointing that out! I've just fixed this in the `latest` (or `5.2.3-dockerupdate-3`) [tag](https://hub.docker.com/repository/docker/erikvl87/languagetool/tags). Could you verify if this has been resolved?

**Comment by tja** [comment]
I was able to verify that this works as expected now.

Thanks for the fix.. I really appreciate it!

**Comment by Erikvl87** [comment]
Thank you for verifying!
